// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffehhiprrwwmnykxvfpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmZWhoaXBycnd3bW55a3h2ZnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDEyMjcsImV4cCI6MjA2NzIxNzIyN30.JJovO51oWVqB3US5hd836QH5v2GNT628-FcEoe2v8FI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});